# =====================================================================
# SonarQube Cloud Configuration for CloudBasket Platform
# =====================================================================

sonar.organization=dharineeshv
sonar.projectKey=dharineeshv_E-Commerce-Backend-API-s-IDP
sonar.projectName=E-Commerce-Backend-API-s-IDP
sonar.projectVersion=1.0.0

# Source Directories to Analyze
sonar.sources=CloudBasket-Frontend,authentication-service,cart-service,inventory-service,marketing-service,notification-service,order-service,payment-service,product-service,review-service,user-profile-service,wishlist-service

# File Exclusions
sonar.exclusions=**/node_modules/**,**/lambda-zips/**,**/*.test.js,**/coverage/**,**/scratch/**,**/*.png,**/*.jpg,**/*.jpeg

# Disable Code Coverage Metrics in SonarQube
sonar.coverage.exclusions=**/*

# Language & Encoding
sonar.sourceEncoding=UTF-8
