service: Dharineesh-review-service

provider:
  name: aws
  runtime: nodejs24.x
  region: ap-southeast-1
  role: arn:aws:iam::726101441380:role/Dharineesh_E-Comm
  environment:
    REVIEW_TABLE: Dharineesh_reviews
    COGNITO_USER_POOL_ID: ap-southeast-1_NPoiPEr2z
    COGNITO_CLIENT_ID: vsuddgu9b60grfe3cj41hoiku

functions:
  app:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
